### ISSUE TITLE
Organize the pkgdown reference section

### ISSUE THREAD

**Issue by gsrohde** [biocro/biocro#41]
Right now, the items in the _Reference_ section of the pkgdown book are simply listed in a list that is alphabetized according to the name of the *.Rd file they are described in.  In particular, functions and named data sets are intermixed.

This list can be curated, so that ordering is more systematic, and related items can be grouped together, as described in the pkgdown documentation, both in the [Reference section of the _Getting Started_ article](https://pkgdown.r-lib.org/articles/pkgdown.html#reference) and in the [description of the `build_reference_index()` function](https://pkgdown.r-lib.org/reference/build_reference.html#reference-index).

I've taken a stab at doing this in the branch [curate_pkgdown_reference_index](https://github.com/biocro/biocro/tree/curate_pkgdown_reference_index)  To view the result, fetch and switch to this branch, open an R session in the root directory of the BioCro package code, and run
```
pkgdown::init_site()
pkgdown::build_reference()
```
This should automatically open the reference index page in your default browser.  If it doesn't, open the file `docs/reference/index.html` in your browser.  (You could simply run `pkgdown::build_site()`, but this takes much longer, as it builds all of the articles (vignettes), which is a lengthy process.)

See if you think this is worth doing.  If it is, adjust the changes on the `curate_pkgdown_reference_index` branch as you see fit and make a pull request.

**Comment by eloch216** [comment]
It's nice to know this is possible, but I think it might not be worth doing at the moment.

In the fairly near future, I would like to split out the crop growth modules into a separate module library repository. The crop model definitions and related data sets will likely move along with them. Eventually, the long term plan is for the `BioCro` R package to only contain core functions that could be used for defining and running _any_ kind of dynamical system.

With this in mind, overriding the default reference settings will just create one more thing to remember when we start splitting out the modules.

**Comment by eloch216** [comment]
If we're not moving forward with this, I would like to delete the related branch (`curate_pkgdown_reference_index`). I want to avoid having millions of branches in the repository, as we had in `biocro-dev`. Since this branch just includes one change to one file, we can simply reproduce it here. It will be easier to reference this way.

The main change is to add a new section called `reference` to the `pkgdown/_pkgdown.yml` file (after `template` and before `navbar`). Scott's example is as follows:
```
reference:
- title: "Data"
- subtitle: "Environmental Data"
  desc: Atomospheric and Weather Data items available from BioCro
  contents:
  - weather
  - cmi_soybean_weather_data
  - catm_data
- subtitle: "Crop Model Definitions"
  contents:
  - crop_model_definitions
  - miscanthus_x_giganteus
  - soybean
  - soybean_clock
  - willow
- subtitle: "Field Data"
  contents:
  - annualDB
  - obsBea
  - obsBeaC
  - obsNaid
- subtitle: Miscellaneous Data
  contents:
  - soil_parameters
- title: "Functions"
- subtitle: "Simulation Functions"
  desc: >
    Functions for running simulations or simulation steps and related
    helper functions
  contents:
  - run_biocro
  - partial_application
  - add_time_to_weather_data
  - get_growing_season_climate
  - dynamical_system
  - module_paste
  - system_derivatives
- subtitle: "Informational Functions"
  desc: "Get information about modules, quantities, and solvers"
  contents:
  - get_all
  - modules
- subtitle: Module test-related functions
  contents:
  - module_testing
  - test_module
  - test_module_library
  - module_case_files
- title: internal # These items will be ignored:
  contents:
  - lightME
  - module_creators
```
